- name: Configure monitoring servers
  hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana
    - node_exporter

- name: Configure application servers
  hosts: app
  become: true
  roles:
    - nginx
    - node_exporter
