pipeline {
  agent any

  environment {
    ANSIBLE_HOST_KEY_CHECKING = 'False'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'mukesh',
            url: 'https://github.com/478mkharb/Ansible.git'
      }
    }

    stage('Deploy Monitoring') {
      steps {
        sh '''
          cd oneclick-monitoring
          ansible-playbook -i inventory/aws_ec2.yml site.yml
        '''
      }
    }
  }
}
