pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps { git branch: 'mukesh', url: 'https://github.com/478mkharb/Ansible.git' }
    }

    stage('Lint') {
      steps { sh 'ansible-lint roles/' }
    }

    stage('Syntax Check') {
      steps { sh 'ansible-playbook deploy.yml --syntax-check' }
    }

    stage('Dry Run') {
      steps { sh 'ansible-playbook deploy.yml --check' }
    }

    stage('Deploy') {
      steps { sh 'ansible-playbook deploy.yml' }
    }
  }
}
