- import_tasks: secrets.yml

- name: Install required packages
  package:
    name:
      - curl
      - tar
    state: present

- name: Create monitoring directory
  file:
    path: "{{ monitoring_dir }}"
    state: directory

- name: Deploy Prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_dir }}/prometheus.yml"
  notify: Restart Prometheus

- name: Deploy Alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: "{{ monitoring_dir }}/alertmanager.yml"
  notify: Restart Alertmanager

- name: Deploy Grafana provisioning
  template:
    src: grafana.yml.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yml
  notify: Restart Grafana
