- include_vars: secrets.yml

- apt:
    name: [curl, tar]
    update_cache: yes

- file:
    path: "{{ monitoring_dir }}"
    state: directory

# Prometheus
- get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- unarchive:
    src: /tmp/prometheus.tar.gz
    dest: "{{ monitoring_dir }}"
    remote_src: yes

- file:
    src: "{{ monitoring_dir }}/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: /usr/local/bin/prometheus
    state: link

- template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_dir }}/prometheus.yml"

# Alertmanager
- get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz
    dest: /tmp/alertmanager.tar.gz

- unarchive:
    src: /tmp/alertmanager.tar.gz
    dest: "{{ monitoring_dir }}"
    remote_src: yes

- file:
    src: "{{ monitoring_dir }}/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: /usr/local/bin/alertmanager
    state: link

- template:
    src: alertmanager.yml.j2
    dest: "{{ monitoring_dir }}/alertmanager.yml"

# Grafana
- apt_key:
    url: https://packages.grafana.com/gpg.key

- apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- apt:
    name: grafana
    state: present
