---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: yes


- name: Ensure python3 and pip are installed
  become: true
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present


- name: Install Kubernetes Python libraries
  become: true
  ansible.builtin.pip:
    name:
      - kubernetes
      - openshift
      - pyyaml
    executable: pip3


- name: Detect k3s kubeconfig
  become: true
  stat:
    path: /etc/rancher/k3s/k3s.yaml
  register: k3s_kubeconfig


- name: Detect kubeadm kubeconfig
  become: true
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_kubeconfig


- name: Fail if no kubeconfig found
  fail:
    msg: >
      Kubernetes kubeconfig not found.
      Ensure Kubernetes (k3s or kubeadm) is installed before running monitoring role.
  when:
    - not k3s_kubeconfig.stat.exists
    - not kubeadm_kubeconfig.stat.exists


- name: Set kubeconfig source path
  set_fact:
    kubeconfig_src: >-
      {{
        '/etc/rancher/k3s/k3s.yaml'
        if k3s_kubeconfig.stat.exists
        else '/etc/kubernetes/admin.conf'
      }}



- name: Ensure ubuntu .kube directory exists
  become: true
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Copy kubeconfig for ubuntu
  become: true
  copy:
    src: "{{ kubeconfig_src }}"
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: '0644'


- name: Fix kubeconfig server address (non-localhost)
  become: true
  replace:
    path: /home/ubuntu/.kube/config
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ ansible_host }}:6443"

