- name: Install node exporter
  apt:
    name: prometheus-node-exporter
    update_cache: yes

- name: Enable node exporter
  systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started
