all:
  children:
    monitoring:
      hosts:
        ec2-monitoring.ap-south-1.compute.amazonaws.com:
          ansible_user: ubuntu
    k8s:
      hosts:
        ec2-k8s.ap-south-1.compute.amazonaws.com:
          ansible_user: ubuntu
