all:
  children:
    k8s:
      hosts:
        ec2-k8s-node-public-dns:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/server3.pem
    monitoring:
      hosts:
        ec2-monitoring-node-public-dns:
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/server3.pem
