pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = 'ap-south-1'
    ANSIBLE_HOST_KEY_CHECKING = 'False'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'mukesh',
            url: 'git@github.com:478mkharb/Ansible.git'
      }
    }

    stage('Terraform Apply') {
      steps {
        sh '''
          cd oneclick-monitoring-FINAL/terraform
          terraform init
          terraform apply -auto-approve
        '''
      }
    }

    stage('Configure Servers') {
      steps {
        sh '''
          cd oneclick-monitoring-FINAL/ansible
          ansible-playbook site.yml
        '''
      }
    }
  }
}
