pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = 'ap-south-1'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'mukesh',
            url: 'https://github.com/478mkharb/Ansible.git'
      }
    }

    stage('Terraform Apply') {
      steps {
        dir('oneclick-monitoring-FINAL/terraform') {
          sh '''
            terraform init
            terraform apply -auto-approve
          '''
        }
      }
    }

    stage('Fetch Bastion IP') {
      steps {
        dir('oneclick-monitoring-FINAL/terraform') {
          script {
            env.BASTION_IP = sh(
              script: 'terraform output -raw bastion_public_ip',
              returnStdout: true
            ).trim()
            echo "Bastion IP: ${env.BASTION_IP}"
          }
        }
      }
    }

    stage('Run Ansible') {
      steps {
        dir('oneclick-monitoring-FINAL/ansible') {
            sh """
              export BASTION_IP=${env.BASTION_IP}
              ansible-playbook -vvvv site.yml
            """
          }
        }
      }
    }
  }

