---
---
- name: Install Helm if missing
  include_tasks: helm_install.yml

- name: Add prometheus Helm repo
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
    helm repo update
  args:
    executable: /bin/bash

- name: Create monitoring namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring
    state: present
    kubeconfig: /root/.kube/config
  become: true

- name: Add prometheus Helm repo
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
    helm repo update
  args:
    executable: /bin/bash
  become: true

- name: Deploy kube-prometheus-stack
  community.kubernetes.helm:
    name: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: monitoring
    create_namespace: true
    wait: true
    timeout: 15m
    kubeconfig: /root/.kube/config
  become: true
