- name: Restart Prometheus
  systemd:
    name: prometheus
    state: restarted
    enabled: true

- name: Restart Grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: true

- name: Restart Node Exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: true
