---
- hosts: _k8s_node
  become: true
  gather_facts: false
  tasks:
    - name: test ssm
      command: whoami

  vars:
    ansible_connection: amazon.aws.aws_ssm
    monitoring_namespace: monitoring
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml

  roles:
    - k3s_install
    - monitoring_k8s
