all:
  vars:
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_ed25519

  children:
    app:
      hosts:
        web-server:
          ansible_host: 192.168.81.128
          ansible_user: mukesh

    monitoring:
      hosts:
        centos9:
          ansible_host: 192.168.81.130
          ansible_user: mukeshkharb
