ansible_user: ubuntu

# SSH via bastion with agent forwarding
ansible_ssh_common_args: >
  -o ForwardAgent=yes
  -o ProxyJump=ubuntu@{{ lookup('env','BASTION_IP') }}
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
