pipeline {
    agent any

    environment {
        ANSIBLE_FORCE_COLOR = 'true'
        DASHBOARD_DIR = 'Assignment5/roles/grafana/files'
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

            stage('Fetch Grafana Dashboards') {
                steps {
                    sh '''
                    set -e

                    DASHBOARD_DIR="Assignment5/roles/grafana/files"
                    mkdir -p ${DASHBOARD_DIR}

                    echo "Fetching Grafana dashboards..."

                    curl -fL -o ${DASHBOARD_DIR}/node-exporter.json \
                    https://grafana.com/grafana/dashboards/1860-node-exporter-full/download

                    curl -fL -o ${DASHBOARD_DIR}/prometheus.json \
                    https://grafana.com/grafana/dashboards/19268-prometheus/download

                    curl -fL -o ${DASHBOARD_DIR}/blackbox.json \
                    https://grafana.com/grafana/dashboards/7587-blackbox-exporter-exporter/download

                    echo "Dashboards fetched successfully"
                    '''
        }
    }


        stage('Ansible Syntax Check') {
            steps {
                sh '''
                ansible-playbook site.yml \
                  -i inventory/hosts.yml \
                  --syntax-check
                '''
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh '''
                ansible-playbook site.yml \
                  -i inventory/hosts.yml \
                  -f 5
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Ansible deployment completed successfully'
        }
        failure {
            echo '❌ Ansible deployment failed'
        }
    }
}
