plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1

keyed_groups:
  - key: tags.Role
    prefix: ""
  - key: tags.Project
    prefix: ""

filters:
  tag:Project: oneclick-monitoring
  instance-state-name: running

hostnames:
  - private-ip-address

compose:
  ansible_ssh_common_args: >
    -o ProxyCommand="ssh -W %h:%p ubuntu@3.111.214.15"
