plugin: amazon.aws.aws_ec2

regions:
  - ap-south-1

filters:
  tag:Project: oneclick-monitoring
  instance-state-name: running

keyed_groups:
  - key: tags.Role
    prefix: ""

ccompose:
  ansible_host: >
    {{
      public_ip_address
      if tags.Role == 'bastion'
      else private_ip_address
    }}

  ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=ubuntu@{{ lookup('env','BASTION_IP') }}"
